### ISSUE TITLE
style  properties

### ISSUE THREAD

**Issue by shukenmg** [shadrx/xenforo-minecraft-server-status#1]
when I want to edit the properties I get 

Error
.

Style properties in this style can not be modified. Please try another. 

plz help 

I am using xenforo 1.5.6

**Comment by shadrx** [comment]
Hey @DanTDMMcpe - sorry I didn't see this earlier. I haven't updated this since XenForo 1.2.0 (something has probably changed since then causing it to break) and I don't see myself updating it in the near future, if at all. Unfortunately, I just don't have the time at the moment.
